main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('profil.html',views.profil, name='profil'),
    path('school.html',views.school, name='school'),
    path('about.html',views.about, name='about'),
    path('home.html',views.home, name='home'),
    path('story1.html',views.story1, name='story1'),
    path('story5.html',views.story5, name='story5'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path
from story5.views import masuk,addMatkul,deleteMatkul

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('story5.urls')),
    path('story5/', masuk),
    path('addMatkul/', addMatkul),
    path('deleteMatkul/<int:context_id>', deleteMatkul),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('story5',views.masuk, name='story5'),
    path('story5',views.addMatkul, name='story5'),
]

main/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.
class Matkul (models.Model):
    nama = models.CharField(max_length=100)
    

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

def profil(request):
    return render(request, 'main/profil.html')

def school(request):
    return render(request, 'main/school.html')

def about(request):
    return render(request, 'main/about.html')

def story1(request):
    return render(request, 'main/story1.html')

def story5(request):
    return render(request, 'story5/story5.html')

story5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Matkul

# Create your views here.
def masuk(request):
    matkul = Matkul.objects.all()
    html = 'story5/story5.html'
    context = {'matkul':matkul}
    return render(request, html, context)

def addMatkul(request):
    c = request.POST['nama']
    new_item = Matkul(nama = request.POST['nama'])
    new_item.save()
    return HttpResponseRedirect('/story5/')

def deleteMatkul(request, context_id):
    item_to_delete = Matkul.objects.get(id=context_id)
    item_to_delete.delete()
    return HttpResponseRedirect('/story5/')

main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<center><img src="{%static 'img/tanya.png' %}" width="250" height="250"></center>
<h2>About Me</h2>
<div class="background">
    <div class="transbox">
        <p>Nama saya Bonifasius Erlangga Einsoni Rienko, biasa di panggil Erlang. Kelebihan yang saya miliki 
            adalah saya selalu dapat berusaha membuat diri saya senang, dan selalu bisa berusaha untuk dapat 
            melihat sesuatu dengan baik walaupun sedang dalam masalah. Kelemahan yang 
            saya meiliki adalah mudah panik.</p>
    </div>
    <button class="back"><a href="home.html">
        <p class="welcome">Back</p>
        </a>
</button>
</div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<div class="container">
  <h1>Welcome to My Site</h1>
</div>

<center>
  <button class="profile"><a href="profil.html">
          <img src="{% static 'img/merapi.jpg' %}" width="250" height="250">
          </a>
  </button>
  <p class="welcome">identitas</p>
</center>

<center>
  <button class="profile"><a href="school.html">
          <img src="{%static 'img/logoUI.jpg' %}" width="250" height="250">
          </a>
  </button>
  <p class="welcome">sekolah</p>
</center>

<center>
  <button class="profile"><a href="about.html">
      <img src="{%static 'img/tanya.png' %}" width="250" height="250">
      </a>
</button>
<p class="welcome">about me</p>
</center>

<center>
  <button class="profile"><a href="story1.html">
          <img src="{%static 'img/logoUI.jpg' %}" width="250" height="250">
          </a>
  </button>
  <p class="welcome">Story1</p>
</center>

<center>
  <button class="profile"><a href="{%url 'main:story5' %}">
          <img src="{%static 'img/logoUI.jpg' %}" width="250" height="250">
          </a>
  </button>
  <p class="welcome">Story5</p>
</center>


<div class="container"> 
  <h4>Follow My Social Media</h4>
  <button class="IG"><a href=https://www.instagram.com/bonifasiuserlangga/ target="_blank">
    <img src="{%static 'img/tanya.png' %}" width="80" height="80">
  </a>
  </button>
</div>

{% endblock content %}

main/templates/main/profil.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<center><img src="{% static 'img/merapi.jpg' %}" width="250" height="250"></center>
        <h2>Identitas</h2>
        <div class="background">
            <div class="transbox">
                <p>Nama: Bonifasius Erlangga Einsoni Rienko</p>
                <p>Tempat dan Tanggal Lahir: Klaten, 29 Juni 2001</p>
                <p>Hobi: Photograph</p>
                <p>Kontak: einsoni_rienko (Line)</p>
                <p>Status: Mahasiswa</p>
                <p>Skills: Programming Language(Python dan Java), Mark-up Language(HTML dan CSS)</p>
                <p>Organisasi: Pernah mengikuti UKM UI</p>
            </div>

            <button class="back"><a href="home.html">
                <p class="welcome">Back</p>
                </a>
        </button>

        </div>
{% endblock content %}

main/templates/main/school.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<center><img src="{%static 'img/logoUI.jpg' %}" width="250" height="250"></center>

        <h2>Riwayat Sekolah</h2>
        <div class="background">
            <div class="transbox">
                <p>Playgroup: MaterDei</p>
                <p>Taman Kanak-Kanak: TKK Mater Dei</p>
                <p>Sekolah Dasar: SDK Mater Dei</p>
                <p>Sekolah Menengah Pertama: SMPK Mater Dei</p>
                <p>Sekolah Menengah Atas: SMAN 5 Depok</p>
                <p>Kuliah: Universitas Indonesia, Fakultas Ilmu Komputer, Sistem Informasi</p>
            </div>
            <button class="back"><a href="home.html">
                <p class="welcome">Back</p>
                </a>
        </button>
        </div>  
{% endblock content %}

main/templates/main/story1.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<center> <h1>Tugas PPW</h1> </center>
<center><img src="{%static 'img/logoUI.jpg' %}" width="250" height="250"></center>
<p>   </p>
<p>   </p>
<center><h2>Identitas</h2> </center>
<p>Nama          : Bonifasius Erlangga Einsoni Rienko</p>
<p>NPM           : 1906302850</p>
<p>Hobi          : Photography</p>
<p>Media Sosial  : bonifasiuserlangga (IG)</p>
<p>Warna Favorite: Hitam atau Putih</p>
<p>Tanggal Lahir : 29 Juni 2001</p>
<p>   </p>
<p>   </p>
<center><h2>Riwayat Sekolah</h2> </center>
<p>Playgroup                : Mater Dei</p>
<p>TK                       : TKK Mater Dei</p>
<p>Sekolah Dasar            : SDK Mater Dei</p>
<p>Sekolah Menengah Pertama : SMPK Mater Dei</p>
<p>Sekolah Menengah Atas    : SMAN 5 Depok</p>
<p>Kuliah                   : Universitas Indonesia, Fakultas Ilmu Komputer, Sistem Informasi</p>

<button class="back"><a href="home.html">
    <p class="welcome">Back</p>
    </a>
</button>
{% endblock content %}

story5/templates/story5/readmatkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<center>
<table border="1">
    <thead>
        <tr>
            <th>Nama</th>
        </tr>
    </thead>
    <tbody>                      
        {% for data in matkul  %}                    
       <tr>
        <td>{{data.nama}}</td>
        </tr>
    </tbody>
        {% endfor %}
</table>
</center>
{% endblock content %}

story5/templates/story5/story5.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}

    <center><h1>Jadwal Matkul</h1></center>
    <form action="/addMatkul/"method="post">{% csrf_token %}
        <label for="fname">Nama Matkul</label>
        <input type="text" name="nama">
        <input type="submit" value="Submit">
    </form>

    {% for tambah in matkul %}
        <li>{{tambah.nama}}
            <form action="/deleteMatkul/{{tambah.id}}"
            style="display: inLine;"
            method="post">{% csrf_token %}
                <input type="submit" value="Delete">
            </form>
        </li>
    {% endfor %}
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
</body>
  {% block content %}
  {% endblock content %}
</html>